services:
  ros2_humble_sim:
    build:
      context: ./docker_simulator/DockerFiles
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=docker_control_simulation
        - IMAGE_TAG=0.1
        - WORKSPACE=docker_simulation_ws

    container_name: ros2_humble_simulator
    networks:
      - ros2_internal
    # network_mode: "host"
    # Interactive shell settings
    stdin_open: true
    tty: true
    # Network settings

    # Environment variables
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      # Shell history
      - HISTFILE=/home/ros/.bash_history
      - HISTFILESIZE=10000
      - RCUTILS_COLORIZED_OUTPUT=1
      - GZ_VERSION=harmonic
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all,graphics,display,video,utility,compute
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - OptiX_INSTALL_DIR=/home/ros/NVIDIA-OptiX-SDK-7.2.0-linux64-x86_64
      - IGN_GAZEBO_SYSTEM_PLUGIN_PATH=/home/ros/RGLGazeboPlugin/install/RGLServerPlugin:${IGN_GAZEBO_SYSTEM_PLUGIN_PATH:-}
      - IGN_GUI_PLUGIN_PATH=/home/ros/RGLGazeboPlugin/install/RGLVisualize:${IGN_GUI_PLUGIN_PATH:-}
      - RGL_PATTERNS_DIR=/home/ros/RGLGazeboPlugin/lidar_patterns/

    privileged: true  # Fixed spelling and removed duplicate
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ~/.bash_history:/home/ros/.bash_history
      - ./docker_simulator:/home/ros/docker_simulation_ws
      - /dev/input:/dev/input
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /home/punk-opc/SDK/NVIDIA-OptiX-SDK-7.2.0-linux64-x86_64:/home/ros/NVIDIA-OptiX-SDK-7.2.0-linux64-x86_64
      
      
      

    # Command to source ROS2 environment and start shell
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        echo 'ROS2 humble environment loaded' &&
        bash
      "
    # devices:
    #   - /dev/dri:/dev/dri
    #   - /dev/nvidia0:/dev/nvidia0
    #   - /dev/nvidiactl:/dev/nvidiactl
    #   - /dev/nvidia-modeset:/dev/nvidia-modeset
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ros2_humble_slam:
      build:
        context: ./slam_modules/Dockerfiles
        dockerfile: Dockerfile
        args:
        - IMAGE_NAME=docker_slam_module
        - IMAGE_TAG=0.1
        - WORKSPACE=docker_slam_ws
      container_name: ros2_humble_slam
      networks:
        - ros2_internal
      # network_mode: "host"
      # Interactive shell settings
      stdin_open: true
      tty: true
      # Network settings

      # Environment variables
      environment:
        - DISPLAY=${DISPLAY}
        - QT_X11_NO_MITSHM=1
        - XAUTHORITY=/tmp/.docker.xauth
        - ROS_DOMAIN_ID=0
        - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
        # Shell history
        - HISTFILE=/home/ros/.bash_history
        - HISTFILESIZE=10000
        - RCUTILS_COLORIZED_OUTPUT=1
        - GZ_VERSION=harmonic
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all,graphics,display,video,utility,compute
        - __NV_PRIME_RENDER_OFFLOAD=1
        - __GLX_VENDOR_LIBRARY_NAME=nvidia
        - OptiX_INSTALL_DIR=/home/ros/NVIDIA-OptiX-SDK-7.2.0-linux64-x86_64
      privileged: true  # Fixed spelling and removed duplicate
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        # - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
        - ~/.bash_history:/home/ros/.bash_history
        - ./slam_modules/:/home/ros/docker_slam_ws
        - /dev/input:/dev/input
        - /dev/dri:/dev/dri
        - /dev/nvidia0:/dev/nvidia0
        - /dev/nvidiactl:/dev/nvidiactl
        - /dev/nvidia-modeset:/dev/nvidia-modeset
        - /home/punk-opc/SDK/NVIDIA-OptiX-SDK-7.2.0-linux64-x86_64:/home/ros/NVIDIA-OptiX-SDK-7.2.0-linux64-x86_64
        
        

      # Command to source ROS2 environment and start shell
      command: >
        bash -c "
          source /opt/ros/humble/setup.bash &&
          echo 'ROS2 humble environment loaded' &&
          bash
        "
      # devices:
      #   - /dev/dri:/dev/dri
      #   - /dev/nvidia0:/dev/nvidia0
      #   - /dev/nvidiactl:/dev/nvidiactl
      #   - /dev/nvidia-modeset:/dev/nvidia-modeset
      runtime: nvidia
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]

networks:
  ros2_internal:
    driver: bridge
    